#!/bin/bash

for KVER in `ls -1 atomisp | grep "^[0-9]\+\.[0-9]\+" | sort -V`;
do
    echo "Kernel $KVER:"
    for SYMBOL in `find ./atomisp/$KVER/ -name Kconfig`; do
	grep "^config" $SYMBOL | sed -e "s/config /CONFIG_/g"
    done
done
