# CFLAGS definitions 
ifeq ($(CONFIG_MEDIA_SUPPORT),m)
KBUILD_CFLAGS += -DCONFIG_MEDIA_SUPPORT_MODULE
endif
ifeq ($(CONFIG_MEDIA_PCI_SUPPORT),m)
KBUILD_CFLAGS += -DCONFIG_MEDIA_PCI_SUPPORT_MODULE
endif
ifeq ($(CONFIG_IPU_BRIDGE),m)
KBUILD_CFLAGS += -DCONFIG_IPU_BRIDGE_MODULE
endif
ifeq ($(CONFIG_VIDEO_INTEL_IPU6),m)
KBUILD_CFLAGS += -DCONFIG_VIDEO_INTEL_IPU6_MODULE
endif
ifeq ($(CONFIG_INTEL_VSC),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_VSC_MODULE
endif
ifeq ($(CONFIG_VIDEO_IPU3_CIO2),m)
KBUILD_CFLAGS += -DCONFIG_VIDEO_IPU3_CIO2_MODULE
endif
ifeq ($(CONFIG_INTEL_BXTWC_PMIC_TMU),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_BXTWC_PMIC_TMU_MODULE
endif
ifeq ($(CONFIG_INTEL_BYTCRC_PWRSRC),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_BYTCRC_PWRSRC_MODULE
endif
ifeq ($(CONFIG_INTEL_CHTDC_TI_PWRBTN),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_CHTDC_TI_PWRBTN_MODULE
endif
ifeq ($(CONFIG_INTEL_ISHTP_ECLITE),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_ISHTP_ECLITE_MODULE
endif
ifeq ($(CONFIG_INTEL_MRFLD_PWRBTN),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_MRFLD_PWRBTN_MODULE
endif
ifeq ($(CONFIG_INTEL_PUNIT_IPC),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_PUNIT_IPC_MODULE
endif
ifeq ($(CONFIG_INTEL_ATOMISP2_PDX86),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_ATOMISP2_PDX86_MODULE
endif
ifeq ($(CONFIG_INTEL_ATOMISP2_LED),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_ATOMISP2_LED_MODULE
endif
ifeq ($(CONFIG_INTEL_ATOMISP2_PM),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_ATOMISP2_PM_MODULE
endif
ifeq ($(CONFIG_INTEL_WMI),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_WMI_MODULE
endif
ifeq ($(CONFIG_INTEL_WMI_SBL_FW_UPDATE),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_WMI_SBL_FW_UPDATE_MODULE
endif
ifeq ($(CONFIG_INTEL_WMI_THUNDERBOLT),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_WMI_THUNDERBOLT_MODULE
endif
ifeq ($(CONFIG_INTEL_TELEMETRY),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_TELEMETRY_MODULE
endif
ifeq ($(CONFIG_INTEL_SAR_INT1092),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_SAR_INT1092_MODULE
endif
ifeq ($(CONFIG_STAGING),m)
KBUILD_CFLAGS += -DCONFIG_STAGING_MODULE
endif
ifeq ($(CONFIG_STAGING_MEDIA),m)
KBUILD_CFLAGS += -DCONFIG_STAGING_MEDIA_MODULE
endif
ifeq ($(CONFIG_INTEL_ATOMISP),m)
KBUILD_CFLAGS += -DCONFIG_INTEL_ATOMISP_MODULE
endif
ifeq ($(CONFIG_VIDEO_ATOMISP),m)
KBUILD_CFLAGS += -DCONFIG_VIDEO_ATOMISP_MODULE
endif
ifeq ($(CONFIG_VIDEO_ATOMISP_OV2722),m)
KBUILD_CFLAGS += -DCONFIG_VIDEO_ATOMISP_OV2722_MODULE
endif
ifeq ($(CONFIG_VIDEO_ATOMISP_GC2235),m)
KBUILD_CFLAGS += -DCONFIG_VIDEO_ATOMISP_GC2235_MODULE
endif
ifeq ($(CONFIG_VIDEO_ATOMISP_MSRLIST_HELPER),m)
KBUILD_CFLAGS += -DCONFIG_VIDEO_ATOMISP_MSRLIST_HELPER_MODULE
endif
ifeq ($(CONFIG_VIDEO_ATOMISP_MT9M114),m)
KBUILD_CFLAGS += -DCONFIG_VIDEO_ATOMISP_MT9M114_MODULE
endif
ifeq ($(CONFIG_VIDEO_ATOMISP_GC0310),m)
KBUILD_CFLAGS += -DCONFIG_VIDEO_ATOMISP_GC0310_MODULE
endif
