# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel multimedia device drivers.
#

# Please keep it alphabetically sorted by directory
# (e. g. LC_ALL=C sort Makefile)
obj-y        +=	intel/
